version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: quiz-postgres
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: madhav
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-api

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_DB: quizdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: madhav
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
      DDL_AUTO: update
      SHOW_SQL: false
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - quiz-network


volumes:
  postgres_data:

networks:
  quiz-network:
